version: "3.9"

services:
    server:
        container_name: prakticum-server
        image: prackicum-server
        env_file:
          ./.env
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
        networks:
        - postgres
        depends_on:
            - postgres
        command:
          ./packages/server/utils/waitForDataBaseConnect/wait-for.sh postgres:${POSTGRES_PORT} -- node /app/packages/server/dist/index.js

    postgres:
      image: postgres:14
      env_file:
        ./.env     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      networks:
        - postgres

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4:5.7
      environment:
        PGADMIN_DEFAULT_EMAIL: "pguser@test.com"
        PGADMIN_DEFAULT_PASSWORD: "pgadminuser"
        PGADMIN_CONFIG_SERVER_MODE: "False"
      ports:
        - "5050:80"
      restart: always
      networks:
        - postgres

networks:
    postgres:
      driver: bridge


