version: "3.9"

services:
    webserver:
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      tty: true
      volumes:
        - ./packages/client/nginx.conf:/etc/nginx/nginx.conf
        - ./packages/client/dist:/app/
      ports:
        - "80:80"
      networks:
        - postgres
      depends_on:
        - server
  
    server:
        container_name: prakticum-server
        image: prackicum-server
        env_file:
          ./.env
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
        networks:
        - postgres
        depends_on:
            - postgres
        command:
          ./packages/server/utils/waitForDataBaseConnect/wait-for.sh postgres:${POSTGRES_PORT} -- node /app/packages/server/dist/index.js

    postgres:
      image: postgres:14
      env_file:
        ./.env     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      networks:
        - postgres

networks:
    postgres:
      driver: bridge
      


